name: Build and Upload Docker Image to ECR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build-scan-push-pr:
    if: github.event_name == 'pull_request'
    uses: SFOE-prometheon/github-terraform-workflows/.github/workflows/ecr-build-scan-push.yml@v9
    with:
      dockerfile: Dockerfile
      build-context: .
      ecr-repository: jouleverne
      image-tag: pr-${{ github.event.pull_request.number }}
      aws-region: eu-central-1
    secrets:
      aws-role: ${{ secrets.SFOE_JOULEVERNE_PIPELINE_ROLE_DEV }}

  build-scan-push-latest:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: SFOE-prometheon/github-terraform-workflows/.github/workflows/ecr-build-scan-push.yml@v9
    with:
      dockerfile: Dockerfile
      build-context: .
      ecr-repository: jouleverne
      image-tag: latest
      aws-region: eu-central-1
    secrets:
      aws-role: ${{ secrets.SFOE_JOULEVERNE_PIPELINE_ROLE_DEV }}

  build-scan-push-release:
    if: github.event_name == 'release'
    uses: SFOE-prometheon/github-terraform-workflows/.github/workflows/ecr-build-scan-push.yml@v9
    with:
      dockerfile: Dockerfile
      build-context: .
      ecr-repository: jouleverne
      image-tag: ${{ github.event.release.tag_name }}
      aws-region: eu-central-1
    secrets:
      aws-role: ${{ secrets.SFOE_JOULEVERNE_PIPELINE_ROLE_DEV }}

  build-scan-push-release-prod:
    if: github.event_name == 'release'
    uses: SFOE-prometheon/github-terraform-workflows/.github/workflows/ecr-build-scan-push.yml@v9
    with:
      dockerfile: Dockerfile
      build-context: .
      ecr-repository: jouleverne
      image-tag: ${{ github.event.release.tag_name }}
      aws-region: eu-central-1
    secrets:
      aws-role: ${{ secrets.SFOE_JOULEVERNE_PIPELINE_ROLE_PROD }}

