[theme]

base="light"
primaryColor="#a784d6ff"
backgroundColor="#ffffffff"
secondaryBackgroundColor="#ececfcff"
textColor="#262730"
font="sans serif"
linkColor="#8860bdff"

[server]

maxUploadSize=10

[client]

toolbarMode="viewer"
showSidebarNavigation=false

[theme.sidebar]

linkColor="#8860bdff"
linkUnderline=false
